### ISSUE TITLE
TASK-4.7: Create a layout for the candidates list

### ISSUE THREAD

**Issue by walidoow** [soen-341-team-placeholder/placeholder-soen341project2023#84]
### Description
Create a mockup showing the candidates list to either accept or rescind their application/invite them to an interview.

### Tasks
- [x] Create a layout for the candidate list
- [x] Design the candidate information card or table row
- [x] Design the accept and rescind actions UI (buttons)
