### ISSUE TITLE
TASK-4.8: Develop the page structure for the job candidates page

### ISSUE THREAD

**Issue by walidoow** [soen-341-team-placeholder/placeholder-soen341project2023#85]
### Description
Following the mockup in #84, develop the static webpage to view the list of candidates.

### Tasks
- [x] Create the basic structure for the candidate list
- [x] Develop table rows for candidate information
- [x] Style the accept and rescind action buttons
