### ISSUE TITLE
TASK-4.10: Integrate the candidate application data with the frontend

### ISSUE THREAD

**Issue by walidoow** [soen-341-team-placeholder/placeholder-soen341project2023#87]
### Description
Integrate the logic actions to perform on candidate data with the frontend using the API.

### Tasks
- [x] Fetch candidates to display
- [x] Display the candidate data in the appropriate UI elements
- [x] Integrate the invite to interview, accept, rescind actions with the frontend
